<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 *
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Authorization in the Control panel</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The module is designed for user authorization in the Control panel.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing module</a></li>
    </ul>
</article>